# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DescriptionBlockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DescriptionBlockWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 224)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        Form.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setMinimumSize(QtCore.QSize(0, 200))
        self.textBrowser_1.setMaximumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.textBrowser_1.setFont(font)
        self.textBrowser_1.setStyleSheet("QTextBrowser#textBrowser_1 {\n"
"    background-color: rgb(220, 217, 209);\n"
"}")
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.horizontalLayout.addWidget(self.textBrowser_1)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
